apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: creative-hub-client
  name: creative-hub-client
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: creative-hub-client
