apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: creative-hub-client
  name: creative-hub-client
spec:
  ports:
    - name: api
      port: 4200
      targetPort: 4200
  selector:
    io.kompose.service: creative-hub-client